library(devtools)
library(testthat)
library(dplyr)
library(tidyr)
library(stringr)

load_all()

use_git()
use_r("rawdataprep")
use_r("rawlist_2_df")
use_r("MA_ST_bind")
use_r("pic_flagging")
use_r("time_flagging")
use_r("transect_max")
use_r("transect_time_minmax")
use_r("ts_table")
use_r("ts_plot")
use_r("output_csv_data")
